{"name": "test_unsuccessful_login_response_body_error_message", "status": "passed", "steps": [{"name": "Try to login with invalid credentials", "status": "passed", "attachments": [{"name": "request url", "source": "cdea377a-db29-4786-bf56-19c14c423cc2-attachment.txt", "type": "text/plain"}, {"name": "response text", "source": "cf33fd1b-fb6b-4a53-a78d-5c785a2bd4d8-attachment.txt", "type": "text/plain"}, {"name": "response status code", "source": "0b14d272-c8cb-420c-96a7-79f318f9e156-attachment.txt", "type": "text/plain"}, {"name": "response cookies", "source": "0076414c-f97e-444a-bb98-e2f483d875ab-attachment.txt", "type": "text/plain"}, {"name": "request body", "source": "fd6bc323-7551-4164-9c6d-79e8726eb5d5-attachment.json", "type": "application/json"}], "start": 1715269126469, "stop": 1715269128117}, {"name": "Check the error message in the response body", "status": "passed", "start": 1715269128118, "stop": 1715269128118}], "attachments": [{"name": "log", "source": "f4a1886d-e97d-4603-a3e4-978c295d2101-attachment.txt", "type": "text/plain"}], "start": 1715269126469, "stop": 1715269128118, "uuid": "2be25b8e-f8c7-4ce3-99ba-13fffaae5c88", "historyId": "8d26f03d4623fb3d37e8caee297ba065", "testCaseId": "8d26f03d4623fb3d37e8caee297ba065", "fullName": "tests.api.test_login#test_unsuccessful_login_response_body_error_message", "labels": [{"name": "layer", "value": "api"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "PC-IV"}, {"name": "thread", "value": "6384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_login"}]}